#禁用内嵌Web容器
spring:
  main:
    web-application-type: none
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 13879640liu
    url: jdbc:mysql://localhost:3306/tacos?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2b8
    username: root