spring:
  kafka:
    bootstrap-servers:
      - localhost:9092
    template:
      default-topic: tacocloud.orders.topic
    producer:
      key-serializer: org.springframework.kafka.support.serializer.StringDeserializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer