spring:
  # 这里给出的值实际上是默认值。但它们在这里被明确设置为设置Artemis属性的示例。
  jms:
    template:
      default-destination: tacocloud.order.queue
  artemis:
    host: localhost
    # port: 61616
    port: 8083
    user: admin
    password: admin
    embedded:
      enabled: false