management:
  endpoint:
    health:
      show-details: always
  endpoints:
    jmx:
      exposure:
        include: '*'
    web:
      exposure:
        include: '*'
  server:
    port: 443
    ssl:
      enabled: true
      key-store-type: PKCS12
      key-store: classpath:8934989_www.lezoc.top.pfx
      key-store-password: 1v73yk2a
spring:
  application:
    name: tacos-security-custom
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 13879640liu
    url: jdbc:mysql://localhost:3306/tacos?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2b8
    username: root
  jpa:
    database: MYSQL
    database-platform: org.hibernate.dialect.MySQL5Dialect
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Shanghai
    hibernate:
      use-new-id-generator-mappings: false
    show-sql: true
  hateoas:
    use-hal-as-default-json-media-type: false
  security:
    user:
      name: lc
      password: 13879640liu
  thymeleaf:
    cache: true
    check-template: true
    check-template-location: true
    enabled: true
    encoding: UTF-8
    excluded-view-names: ''
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type: text/html
  data:
    rest:
      base-path: /api
  profiles:
    active:
      - prod
logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
    tacos: DEBUG
taco:
  orders:
    pageSize: 10

  discount:
    codes:
      abcdef: 10


---
spring:
  profiles: prod

logging:
  level:
    tacos: WARN