# 这里给出的值实际上是默认值。
# 但是在这里，它们被显示地设置为Artemis属性的一个示例。
spring:
  jms:
    template:
      default-destination: tacocloud.order.queue
  artemis:
    host: localhost
    # port: 61616
    port: 8083
    user: admin
    password: admin
    embedded:
      enabled: false
    pool:
      enabled: true # 是否创建 JmsPoolConnectionFactory 连接池
      idle-timeout: 30s # 空闲连接超时时间
      max-connections: 50 # 连接池中最大连接数
      max-sessions-per-connection: 100 # 每个连接最大会话